# Generated by Django 3.1 on 2022-10-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_productvariations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVariations',
            new_name='ProductVariation',
        ),
    ]
