# Generated by Django 3.1 on 2023-01-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_auto_20230121_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
